# Generated by Django 3.1.7 on 2021-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uname', models.SlugField(primary_key=True, serialize=False)),
                ('sdate', models.DateField(auto_now_add=True, null=True)),
                ('edate', models.DateField()),
            ],
        ),
    ]
